name: Build & Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install --immutable
      - name: Run check-all
        run: yarn check-all

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/release-')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Publish validator-errors to npm
        run: npm publish --access public
        working-directory: packages/validator-errors
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish validator-test-utils to npm
        run: npm publish --access public
        working-directory: packages/validator-test-utils
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish validator to npm
        run: npm publish --access public
        working-directory: packages/validator
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
